---
image:
  name: hashicorp/terraform:0.15.1
  entrypoint:
    - /usr/bin/env

variables:
  # If your terraform files are in a subdirectory, set TF_ROOT accordingly
  TF_ROOT: deploy/code

cache:
  paths:
    - .terraform

stages:
  - lint
  - test
  - plan
  - apply
  - destroy

yamllint:
  image: sdesbure/yamllint
  stage: lint
  before_script:
    - cd ${TF_ROOT}
  script:
    - yamllint .

fmt-check:
  stage: lint
  before_script:
    - cd ${TF_ROOT}
  script:
    - terraform fmt -recursive

validate:
  stage: test
  before_script:
    - cd ${TF_ROOT}
    #- echo $tfc_credentials > /root/.terraformrc
  script:
    - terraform init
    - terraform version
    - terraform validate

plan:
  stage: plan
  before_script:
    - cd ${TF_ROOT}
    #- echo $tfc_credentials > /root/.terraformrc
  script:
    - terraform init
    - terraform plan -out out.tfplan
    - terraform show -json out.tfplan > tfplan.json
  artifacts:
    expire_in: 8 weeks
    paths:
      - out.tfplan
      - tfplan.json

apply:
  stage: apply
  before_script:
    - cd ${TF_ROOT}
    #- echo $tfc_credentials > /root/.terraformrc
  script:
    - terraform init
    - terraform apply -input=false out.tfplan
  when: manual
  only:
    - master

destroy:
  stage: destroy
  before_script:
    - cd ${TF_ROOT}
    #- echo $tfc_credentials > /root/.terraformrc
  script:
    - terraform init
    - terraform destroy -auto-approve
  when: manual
  only:
    - master

#infracost:
#  stage: infracost
#  image:
    # Always use the latest 0.9.x version to pick up bug fixes and new resources.
    # See https://www.infracost.io/docs/integrations/cicd/#docker-images for other options
#    name: infracost/infracost:ci-0.9
#    entrypoint: [""] # Override since we're running commands below
#  dependencies:
#    - plan
#  script:
#    - infracost breakdown --path ${TF_ROOT}/full-plan.json --format json --out-file infracost.json
#    - /scripts/ci/comment.sh infracost.json
#  variables:
#    INFRACOST_API_KEY: $INFRACOST_API_KEY

